version: '3.7'

services:
  payment-calculator-backend:
    container_name: payment-calculator-backend
    image: payment-calculator-backend:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
  payment-calculator-frontend:
    container_name: payment-calculator-frontend
    image: payment-calculator-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://payment-calculator-backend:8080
    volumes:
      - ./node_modules:/payment-calculator-frontend/node_modules
networks:
  app-network:
    driver: bridge
